"""auth_columns_and_otp_logs

Revision ID: 02538f8be184
Revises: e5de1042d0dd
Create Date: 2026-03-03 16:39:32.193303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02538f8be184'
down_revision: Union[str, Sequence[str], None] = 'e5de1042d0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add SUPER_ADMIN to the PostgreSQL enum (autogenerate misses enum changes)
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SUPER_ADMIN'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('can_access_kitchen', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_access_waiter', sa.Boolean(), nullable=True))
    op.alter_column('users', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'can_access_waiter')
    op.drop_column('users', 'can_access_kitchen')
    op.drop_table('otp_logs')
    # ### end Alembic commands ###
