"""add_process_config_and_order_snapshot

Revision ID: 583855d02f84
Revises: ebb82d252f12
Create Date: 2026-03-05 02:28:02.617179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583855d02f84'
down_revision: Union[str, Sequence[str], None] = 'ebb82d252f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('kitchen_module', sa.Boolean(), nullable=False),
    sa.Column('waiter_module', sa.Boolean(), nullable=False),
    sa.Column('owner_dashboard', sa.Boolean(), nullable=False),
    sa.Column('customer_status_tracking', sa.Boolean(), nullable=False),
    sa.Column('menu_management', sa.Boolean(), nullable=False),
    sa.Column('staff_management', sa.Boolean(), nullable=False),
    sa.Column('owner_can_configure', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.add_column('orders', sa.Column('process_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'process_snapshot')
    op.drop_table('process_configs')
    # ### end Alembic commands ###
