"""add_logo_url_to_restaurants

Revision ID: ebb82d252f12
Revises: 02538f8be184
Create Date: 2026-03-03 21:03:59.789957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb82d252f12'
down_revision: Union[str, Sequence[str], None] = '02538f8be184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'logo_url')
    # ### end Alembic commands ###
